# frozen_string_literal: true

source 'http://mirrors.tuna.tsinghua.edu.cn/rubygems'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'sinatra', '4.1.1'
gem 'rack', '~> 3.0'
gem 'sinatra-contrib'
gem 'sinatra-cross_origin'
gem 'sinatra-websocket'
gem 'json'
gem 'redis'
gem 'jwt'
gem 'rack-cors'
gem 'opal'
gem 'opal-jquery'
gem 'opal-sprockets'
gem 'faraday'
gem 'radius'
gem 'thin'
gem 'sinatra-flash'
gem 'mongo'

group :development do
  gem 'pry'
  gem 'pry-byebug'
  gem 'sinatra-reloader'
end